POST http://localhost:8081/doctors/register
Content-Type: application/json

{
  "did": 5,
  "name" : "Ilya",
  "surname": "Ryabukhin",
  "dType": "Masseuse",
  "password": "ilaila"
}

###
POST http://localhost:8081/doctors/login
Content-Type: application/json

{
  "did": 5,
  "password": "ilaila"
}

###
POST http://localhost:8081/patients/register
Content-Type: application/json

{
  "pid": 2,
  "email" : "grech@dan.com",
  "name" : "Daniel",
  "surname": "Grechany",
  "age": 22,
  "password": "dandan"
}

###
POST http://localhost:8081/patients/login
Content-Type: application/json

{
  "email" : "grech@dan.com",
  "password": "dandan"
}

###
GET http://localhost:8081/patients/1

###
GET http://localhost:8081/doctors/2


###
PUT http://localhost:8081/patients/2
Content-Type: application/json

{
  "pid": 2,
  "email" : "grech@dan.com",
  "name" : "Daniel",
  "surname": "Grechany",
  "age": 22,
  "password": "dandan"
}
###
PUT http://localhost:8081/doctors/5
Content-Type: application/json

{
  "did": 5,
  "name" : "Ilya",
  "surname": "Ryabukhin",
  "dType": "Masseuse",
  "password": "ilaila"
}
###
DELETE http://localhost:8081/doctors/6
###
DELETE http://localhost:8081/patients/3